spring.datasource.url=jdbc:postgresql://localhost:5432/licklibrary
spring.datasource.username=${USER}
spring.datasource.password=

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
